//using LF1.Universe;
//using IBMU2.UODOTNET;
namespace Compiler
{
public class FL391 : UvBase
{
#region Common instances
COMMON COMMON = COMMON.Instance;
TXLOG TXLOG = TXLOG.Instance;
#endregion
#region Int Constants
readonly UvVar TRUE = 1;
readonly UvVar FALSE = 0;
readonly UvVar OTHERWISE = 1;
readonly UvVar TOP_WINDOW = 1;
readonly UvVar BOTTOM_WINDOW = 2;
readonly UvVar LEFT_WINDOW = 3;
readonly UvVar RIGHT_WINDOW = 4;
readonly UvVar WIDTH = 5;
readonly UvVar CLR_LINE = 6;
readonly UvVar WINDOW_SIZE = 7;
readonly UvVar HEADING_TEXT = 8;
#endregion
#region String Constants
readonly UvVar INIT = "";
#endregion
#region Arrays
UvVar[] WINDOW_PARAMS = new UvVar[10];
#endregion
#region Variables
UvVar TERMINAL_TYPE = "";
UvVar REV_VID = "";
UvVar DIM_REV_VID = "";
UvVar NRM_VID = "";
UvVar CUR_BACK = "";
UvVar CUR_DOWN = "";
UvVar PROGRAM = "";
UvVar BLANK_LINE = "";
UvVar DIM_LINE = "";
#endregion
public FL391(ref UvVar[] WINDOW_PARAMS) {
this.WINDOW_PARAMS = WINDOW_PARAMS;
#region INCLUDE FL.COMMON FL.COMMON

/*  FILES */
/*     Standard */
/*     Screen Control */
/*     Slave Printer Control */
/*     Special Video */
/*     User input control */
/*     Application Specific */
/* COMMON SC.POS */
/*     Theatre */
/*     Standard EQUates */
/*     Client app control */
/* \ */
#region INCLUDE TX.INCLUDE TX.COMMON

#endregion

#endregion
/*  Print Box */
PROGRAM = "FL391";
// BEGIN CASE
// CASE
if (TERMINAL_TYPE == "Y" || TERMINAL_TYPE == "W") {
BLANK_LINE = STR(NRM_VID + CUR_BACK + CUR_DOWN, WINDOW_PARAMS[BOTTOM_WINDOW] - WINDOW_PARAMS[TOP_WINDOW] - 1);
DIM_LINE = STR(DIM_REV_VID + CUR_BACK + CUR_DOWN, WINDOW_PARAMS[BOTTOM_WINDOW] - WINDOW_PARAMS[TOP_WINDOW] - 1);
}// CASE
else if (OTHERWISE) {
BLANK_LINE = STR(NRM_VID + CUR_BACK + CUR_DOWN, WINDOW_PARAMS[BOTTOM_WINDOW] - WINDOW_PARAMS[TOP_WINDOW] - 1);
DIM_LINE = STR(DIM_REV_VID + CUR_BACK + CUR_DOWN, WINDOW_PARAMS[BOTTOM_WINDOW] - WINDOW_PARAMS[TOP_WINDOW] - 1);
}
// END CASE
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW] - 1, WINDOW_PARAMS[TOP_WINDOW]) + STR(COMMON.EOL + CUR_DOWN, WINDOW_PARAMS[BOTTOM_WINDOW] - WINDOW_PARAMS[TOP_WINDOW] + 1));
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW] + 1, WINDOW_PARAMS[TOP_WINDOW] + 1) + BLANK_LINE);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[TOP_WINDOW] + 1) + BLANK_LINE);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[TOP_WINDOW]) + NRM_VID);
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW] - 1, WINDOW_PARAMS[TOP_WINDOW]) + REV_VID);
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW], WINDOW_PARAMS[TOP_WINDOW]) + WINDOW_PARAMS[CLR_LINE] + "    ");
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW], WINDOW_PARAMS[TOP_WINDOW]) + WINDOW_PARAMS[HEADING_TEXT]);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[TOP_WINDOW]) + NRM_VID);
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW] - 1, WINDOW_PARAMS[TOP_WINDOW] + 1) + DIM_LINE);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[TOP_WINDOW] + 1) + NRM_VID);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] - 1, WINDOW_PARAMS[TOP_WINDOW] + 1) + DIM_LINE);
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[BOTTOM_WINDOW]) + NRM_VID);
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW] - 1, WINDOW_PARAMS[BOTTOM_WINDOW]) + DIM_REV_VID);
PRINT(AT(WINDOW_PARAMS[LEFT_WINDOW], WINDOW_PARAMS[BOTTOM_WINDOW]) + WINDOW_PARAMS[CLR_LINE] + "    ");
PRINT(AT(WINDOW_PARAMS[RIGHT_WINDOW] + 1, WINDOW_PARAMS[BOTTOM_WINDOW]) + NRM_VID);
return;
}
}
}
